#!/usr/bin/env bash
# This script is displaying a string indefinitely and handles a SIGTERM signal

i=1
while [ $i -eq 1 ]; do
    trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
