#!/usr/bin/env bash
# Displays 1 to 100 where "FizzBuzz" is displayed if the number is a multiple
# of 3 and 5, "Fizz" if the number is a multiple of 3, and "Buzz" if the
# number is a multiple of 5. Otherwise it displays the number

i=1
for i in {1..100}; do
      if [ $((i%5)) == 0 ] && [ $((i%3)) == 0 ]; then
        echo "FizzBuzz"
      elif [ $((i%5)) == 0 ]; then
        echo "Buzz"
      elif [ $((i%3)) == 0 ]; then
        echo "Fizz"
      else
        echo "$i"
      fi
done