#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but for the 9th iteration, displays "Hi"

i=0
while [ $i -lt 10 ]; do
      echo "Holberton School"
      i=$((i+1))
      if [ $i == 9 ]; then
	    echo "Hi"
      fi
done
